### PR TITLE
Remove jQuery CDN feature

### LINKED ISSUE #226: WP 5.2.1 and the custom patched jQuery breaks the soil-jquery-cdn due to -wp in version string
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

In WordPress 5.2.1 The jQuery version was custom patched for the vulnerability found in 1.12.4. This appended a '-wp' to the version string breaking the soil-jquery-cdn module as it used the version to call the external CDN.
Core Ticket - https://core.trac.wordpress.org/ticket/47020
Changesets;
https://core.trac.wordpress.org/changeset/45354
https://core.trac.wordpress.org/changeset/45342

This was also reported in core recently;
https://core.trac.wordpress.org/ticket/47342

I don't see Core fixing this so would suggest a str_replace, which I'll PR shortly here.

## Steps to reproduce

1. Setup theme.
2. Enable soil-jquery-cdn - ```add_theme_support('soil-jquery-cdn');       // Enable to load jQuery from the Google CDN```
3. Upgrade to WordPress 5.2.1
4. You'll find all jQuery fails on site as it gives a 404 response since the CDN doesn't have the version w/ -wp on it.

**Expected behavior:**
jQuery should just load, would suggest either stripping the '-wp' or setting a hardcoded version.

**Actual behavior:**
jQuery fails to load form CDN giving WSOD or other jQuery issues.

**Reproduces how often:**
100% of page loads

## Versions

WordPress - 5.2.1
jQuery - 1.12.4-wp
Soil - 3.5.0
Sage - 8.2.1

### PR DESCRIPTION
**Pull request by retlehs**
as of wordpress 5.2.1, wp core decided to add `-wp` to their custom patched version of jquery

see: https://core.trac.wordpress.org/ticket/47020

and it doesn't look like jquery 3.x will land any time soon: https://core.trac.wordpress.org/ticket/37110

jquery is something that's still used by a whole lot of wordpress plugins, but we're going to go ahead and remove support for this feature in soil. the way that core has and continues to deal with jquery is something i'd rather not support.

**recommended plugin for retaining similar functionality: https://wordpress.org/plugins/commonwp/**

[regarding this comment](https://core.trac.wordpress.org/ticket/47342#comment:7) from wp core developer azaozz:

> Thanks for alerting the devs of Roots Soil. The "proper" solution would be to stop loading the unpatched jQuery from a CDN, and load the patched version from WP.

the "proper" solution is for wordpress core to not manually backport jquery patches into their custom version of jquery, and actually upgrade to a version that is ancient (3.x), but at least not prehistoric (1.x) 💋  

close #226 
close #227 
close #225

### CODE REVIEW

**Comment by garrett-eclipse** [comment]
Thanks @retlehs good call. All the best

**Comment by DanielRuf** [comment]
> the "proper" solution is for wordpress core to not manually backport jquery patches into their custom version of jquery, and actually upgrade to a version that is ancient (3.x), but at least not prehistoric (1.x) 💋

Hi there, I am the person who created the backported patches.

Upgrading is often not a solution as this breaks many things.

A string at the end of a version is still valid SemVer afaik.

**Comment by coliff** [comment]
Now that WordPress uses jQuery 3.5.1 perhaps the jQuery CDN feature could be re-introduced?

**Comment by strarsis** [comment]
@coliff, @retlehs: The same topic came up in the Sage 9.1 update branch PR.
Never used this feature myself, but should it be re-introduced with the current browser-, WordPress-, stack-landscape in 2021?

**Pull request merged**
