### PR TITLE
Enable jQuery noConflict

### PR DESCRIPTION
**Pull request by retlehs**
this enables `jQuery.noConflict();` just like WP does ¯\_(ツ)_/¯

ref #155

### CODE REVIEW

**Comment by timsamuelsson** [comment]
Would it be possible to make this optional? We are using soil on alot of sites and the update craches our js.

**Comment by retlehs** [comment]
what does "crashes our js" mean exactly

**Comment by timsamuelsson** [comment]
All our js is written without the no conflict mode witch mean that it wount work because we use $ everywhere.

**Comment by retlehs** [comment]
So you wrote your JavaScript in a way that it shouldn't have been written. Fix your JS or use a previous version of the plugin.

**Comment by timsamuelsson** [comment]
Hi,

Sorry for a late answer.
Could you explain to me why its wrong to use jQuery without the no conflict mode.

I would be super happy if this could be a setting like define('ROOTS_JQUERY_FALLBACK_NO_CONFLICT, false) or similar.

//Tim

**Comment by QWp6t** [comment]
WordPress by default uses `.noConflict()`. We're maintaining parity.

It's trivial to fix your script. Just wrap it in an IIFE.

```js
;(function($) {
  // $() can be used in here...
})(jQuery);
```

**Comment by timsamuelsson** [comment]
Thanks, would it work if i wrap my hole js build with that in my gulp job?

**Pull request merged**
