### PR TITLE
Properly make URLs relative when using multisite with domain mapping & use parse_url function instead of regex for parsing URLs

### PR DESCRIPTION
**Pull request by aaronhuisinga**

### CODE REVIEW

**Comment by joemaller** [comment]
:+1: on this. 

I just found a related issue we might want to roll in since it's the same line. It's kind of an edge case though.

Because wp-cli doesn't have a `$_SERVER` context, [the conditional on line 16](https://github.com/aaronhuisinga/soil/blob/14fc45b3ce919571b4fb79feddeec926820559ee/lib/utils.php#L16) ([line 13 upstream](https://github.com/roots/soil/blob/bfb4d3724872e1e555a663580ec8fc22b9417514/lib/utils.php#L13)) throws hundreds of notices when running the `wp export` command in a shell when `php_error_reporting` is set to `E_ALL`:

> `PHP Notice:  Undefined index: SERVER_PORT in /srv/www/example.com/current/web/app/plugins/soil/lib/utils.php on line 16`

> `Notice: Undefined index: SERVER_PORT in /srv/www/example.com/current/web/app/plugins/soil/lib/utils.php on line 16`

Repeat until scrollback fills. 

Putting `$url['host'] === $network_url` at the end of that condition makes it hard to rearrange *(and see, is there project code-style guidance for breaking extra-long conditionals?)*. I don't have any experience with multisite WP, but it seems like that condition might be plausible even if `$_SERVER` isn't defined.

**Comment by retlehs** [comment]
@joemaller could you pls submit a PR?

**Comment by austinpray** [comment]
Help me @joemaller you are my only hope

**Comment by vinkla** [comment]
chosen

**Pull request merged**
