### PR TITLE
fix: typo in extended options documentation

### PR DESCRIPTION
**Pull request by greatislander**
This PR fixes a typo in the README (`disable_rececent_comments_css` instead of `disable_recent_comments_css`).

### CODE REVIEW

**Comment by QWp6t** [comment]
Technically the documentation is correct since the same typo exists in the code. 😬

If you wanna fix it in the module too, we can merge this.

https://github.com/roots/soil/blob/master/src/Modules/CleanUpModule.php#L87

🙈

**Comment by greatislander** [comment]
Oh! Sure! 😹

**Comment by greatislander** [comment]
@QWp6t That should do it :)

**Comment by QWp6t** [comment]
Thanks for the PR! 🎉

**Pull request merged**
