### PR TITLE
Add .gitattributes

### PR DESCRIPTION
**Pull request by vinkla**
This way we can exclude files when installing the package with `composer install --prefer-dist`.

### CODE REVIEW

**Comment by retlehs** [comment]
why exclude the CHANGELOG and README?

looks like you're still including CONTRIBUTING, which is one we have specified to exclude right now

**Comment by vinkla** [comment]
> why exclude the CHANGELOG and README?

It wont affect development. It is common to exclude these files for production.

> looks like you're still including CONTRIBUTING…

Is there a CONTRIBUTING file?

**Comment by retlehs** [comment]
ah yes, no CONTRIBUTING file in this repo (that part of our `composer.json` file is from [here](https://github.com/roots/wp-password-bcrypt))

README and CHANGELOG files are still relevant for production

**Comment by vinkla** [comment]
> README and CHANGELOG files are still relevant for production

Why are they still relevant for production? Don't we want to keep production as clean as possible? I mean, if this an application is pushed to production we wont go there and view the source code.

**Comment by vinkla** [comment]
Personally I never read changelogs or documentation in production. I either check my local development environment or GitHub.

**Comment by QWp6t** [comment]
We should only be removing git and CI related stuff. We want to distribute our CHANGELOG.md and README.md, especially for people who download a zip of this repo.

**Comment by vinkla** [comment]
> We want to distribute our CHANGELOG.md and README.md

That is an argument I agree with. Since this is WordPress plugin. I'll update the pull-request.

**Comment by vinkla** [comment]
Done.

**Comment by retlehs** [comment]
thanks

**Pull request merged**
