### PR TITLE
Badges!

### PR DESCRIPTION
**Pull request by QWp6t**

### CODE REVIEW

**Comment by austinpray** [comment]
No way I'm letting this get merged with this non-flat badge

screenshot 2015-05-04 11 44 39

**Comment by vinkla** [comment]
Nice! Maybe you should consider using http://shields.io/ instead. Their badges all looks and works the same. What do you think?

**Comment by austinpray** [comment]
yee

**Comment by vinkla** [comment]
@austinpray much better!

**Comment by retlehs** [comment]
keep it simple

**Comment by austinpray** [comment]
image

**Comment by kalenjohnson** [comment]
Nailed it

**Comment by QWp6t** [comment]
yeah, that looks great! can you submit a new pr?

**Pull request closed without merging**
