### PR TITLE
Add check to body_class for page slug to avoid duplication

### PR DESCRIPTION
**Pull request by Tidal-Wave**
I somehow borked my other fork so I am redoing this [PR]. (https://github.com/roots/soil/pull/32)
PR has been rebased at @retlehs request.

### CODE REVIEW

**Comment by retlehs** [comment]
rebase to squash into 1 commit and we're good :+1:

**Comment by Tidal-Wave** [comment]
Yea sorry, my git-ninja level is on the fritz today, I blame hunger. On that as soon as I eat lunch.

**Comment by Tidal-Wave** [comment]
I think that should do it, let me know if my hunger messed anything else up.

**Comment by retlehs** [comment]
ty sir

**Pull request merged**
