### PR TITLE
Don't lose additional query string arguments on redirect

### PR DESCRIPTION
**Pull request by goblindegook**
The nicer search module currently discards all additional query string arguments on redirect. This patch should fix that, so that links like `/?s=query&post_type=cpt` get changed to `/search/query?post_type=cpt`.

### CODE REVIEW

**Comment by retlehs** [comment]
let's leave nice search as is, and let people figure out their own URL design for more advanced queries (e.g. `/search/books/art-of-war/`)

**Comment by goblindegook** [comment]
Just to be clear, this isn't about letting people design their URLs, but fixing core functionality that the plugin breaks, namely the ability to perform faceted searches.

**Comment by retlehs** [comment]
slapping on `?post_type=cpt` to the end of the query is not a solution for 'nice search', which is why it should probably be left up to a dev to figure out how they want to design their URLs for anything besides the basic search queries.

**Comment by goblindegook** [comment]
If devs are supposed to figure out how to design their URLs, why not give them a feature that works first, and only then let them take it from there? Having a beautiful URL to look at is a nice extra, but it's not really the point of search. Completely disabling complex queries without so much as a warning is not "nice" at all.

**Comment by retlehs** [comment]
i'm open to a PR that disables the nice search functionality if there's any sort of variables

**Comment by goblindegook** [comment]
But this PR does just that: if there are additional query string variables, it doesn't discard them. Simple search works the same. It doesn't add any variables you didn't put there in the first place. Sorry I wasn't clear in my initial description.

—

**Comment by retlehs** [comment]
we don't need +12 lines to simply disable nice search from running if there's any `$_GET` variables

**Comment by goblindegook** [comment]
Don't see the point of disabling it completely, I'm afraid. You can keep the pretty permalink structure and add the extra query vars.

—

**Comment by adanarchila** [comment]
Thanks for your commit @goblindegook it helped me, and I agree with your point is not that "nice" if is not useful.

**Pull request closed without merging**
