### PR TITLE
The SEO Framework + relative URLs

### LINKED ISSUE #181: Using relative urls with The SEO Framework causes og:image to be relative
This breaks the og:image tag because it must be absolute in order for Facebook to parse it

### PR DESCRIPTION
**Pull request by retlehs**
fixes #181

### CODE REVIEW

**Comment by wassim** [comment]
@retlehs any reasons behind this? The root domain is now duplicated and Facebook/Twitter can't parse it:
```
<meta property="og:image" content="http://domain.com/http://domain.com/app/uploads/..." />
<meta name="twitter:image" content="http://domain.com/http://remotejunior.com/app/uploads/..." />
```

**Comment by retlehs** [comment]
oh boy. things might have changed with a new version of the SEO framework. ill take a look - thanks for reporting

**Comment by JulienMelissas** [comment]
oh damn, glad we haven't push this to production yet...

**Comment by retlehs** [comment]
@wassim i'm unable to reproduce. please post on discourse with more details

**Comment by wassim** [comment]
@retlehs #187

**Comment by wassim** [comment]
@retlehs #187

**Pull request merged**
